# Generated by Django 5.1.5 on 2025-06-29 09:32

import account.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[account.validators.MobileValidator()], verbose_name='شماره همراه')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('user_type', models.CharField(choices=[('patient', 'بیمار'), ('doctor', 'پزشک')], max_length=10, verbose_name='نوع کاربر')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='آخرین آپدیت')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='doctor_images/', validators=[account.validators.validate_avatar_dimensions, account.validators.validate_avatar_size], verbose_name='عکس پروفایل')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[account.validators.NationalCodeValidator()], verbose_name='کد ملی')),
                ('brithday', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('about_me', models.TextField(blank=True, null=True, verbose_name='درباره من')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس')),
                ('Medical_system_code', models.CharField(max_length=12, verbose_name='کد نظام پزشکی')),
                ('specialty', models.CharField(choices=[('ORTHO', 'ارتودانتیکس'), ('PERIO', 'پریودانتیکس'), ('ENDO', 'اندودانتیکس'), ('PROS', 'پروتزهای دندانی'), ('OMFS', 'جراحی فک و صورت'), ('PED', 'دندانپزشکی کودکان'), ('REST', 'دندانپزشکی ترمیمی و زیبایی'), ('OMFR', 'رادیولوژی فک و صورت'), ('OMFP', 'آسیب\u200cشناسی فک و صورت'), ('DPH', 'بهداشت عمومی دندان'), ('IMPL', 'ایمپلنتولوژی')], max_length=30, verbose_name='تخصص')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='سابقه کاری')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پزشک',
                'verbose_name_plural': 'پزشکان',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='cldOFMRl4v0Lf850ClXEbbwTwJxDi2DTUcwsIHd4sVGD9tR0fY867tXYKYdXH6l5KxrCGl0YE3COSi8RG0RzzhmcJOjW6f63gy04zK7m30eEe94jtNMfO7OJuC2UfHyuKRWKb8dQdfpUvHNcjfaI9qqWWgtJxmN0zHLFUAFFWtqGLDN1rGzo6czMlfFso421TFcwMJ6RTn0TXOThUlrHOSxrrtXEtilCNYpyOwlIA2xNqzOkPewKRPG5vr', max_length=300, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'توکن ریست کلمه عبور',
                'verbose_name_plural': 'توکن های ریست کلمه عبور',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='آخرین آپدیت')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='doctor_images/', validators=[account.validators.validate_avatar_dimensions, account.validators.validate_avatar_size], verbose_name='عکس پروفایل')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[account.validators.NationalCodeValidator()], verbose_name='کد ملی')),
                ('brithday', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('about_me', models.TextField(blank=True, null=True, verbose_name='درباره من')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس')),
                ('gender', models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن')], max_length=6, null=True, verbose_name='جنسیت')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بیمار',
                'verbose_name_plural': 'بیماران',
            },
        ),
    ]
