# Generated by Django 5.1.5 on 2025-07-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default='4Hq8sqw0NCtsV7LOz2qQu8XiXp1CDPBMT4NxMRSjdVun2QC3d5HD1lzraJAQdwiUE44xkypP6kMLSxT3G5b65reqBLBI4YiU5yIDmHoxEXaf2l2dRuK5xbBQRuPMISbs6ft4GlLaNA7MvGZc41zfzx2sNsw2zjXDSZWPLgjtoW3HVGATUSbY2zpoSHAlyurNV89cLDYSRAydOs12yEh5czKpc9Aa36qvBz6bVlN8EqjRw3xJTsuVz8pi7N', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
