# Generated by Django 5.1.5 on 2025-07-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_passwordresettoken_token_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default='wuNAolQP6Y4g5XdNXbVDcgx3TgYEp4Q0UEPyfAMRdXGfRxqx5rfaK460UKaNytSqz1C2JJCytbEoofZ5njqrtia5JRAoeyrpJQmMilqSypeChspz5sQGnflGRMhCsfctwIi9Z0I4hfKEeau3rRggPZUJch2L7mujMaRBXgqD3BKClhTO3TN0KE5owp8pB269cLzK8VVqJnJY1YariYX6zJV1i1QA6iTRJqQTz87uDXuFLlY2viI9oZXcG7', max_length=300, unique=True),
        ),
    ]
