# Generated by Django 5.1.5 on 2025-01-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_otpcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'پزشک', 'verbose_name_plural': 'پزشکان'},
        ),
        migrations.AlterModelOptions(
            name='otpcode',
            options={'verbose_name': 'کد تایید', 'verbose_name_plural': 'کد های تایید'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'بیمار', 'verbose_name_plural': 'بیماران'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_images/', verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_images/', verbose_name='عکس پروفایل'),
        ),
    ]
