# Generated by Django 5.1.5 on 2025-01-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_doctor_options_alter_otpcode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'پزشک'), ('patient', 'بیمار')], default='patient', max_length=10),
        ),
    ]
