# Generated by Django 5.1.5 on 2025-02-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Medical_system_code',
            field=models.CharField(default='', max_length=12, unique=True, verbose_name='کد نظام پزشکی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='ایمیل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='', max_length=100, verbose_name='نام و نام خانوادگی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience_years',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='سابقه کاری'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('patient', 'بیمار'), ('doctor', 'پزشک')], max_length=10, verbose_name='نوع کاربر'),
        ),
    ]
