# Generated by Django 5.1.5 on 2025-02-07 13:48

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_doctor_user_alter_patient_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={'verbose_name': 'توکن ریست کلمه عبور', 'verbose_name_plural': 'توکن های ریست کلمه عبور'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='about_me',
            field=models.TextField(blank=True, null=True, verbose_name='درباره من'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_images/', validators=[account.validators.validate_avatar_dimensions, account.validators.validate_avatar_size], verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='brithday',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='about_me',
            field=models.TextField(blank=True, null=True, verbose_name='درباره من'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_images/', validators=[account.validators.validate_avatar_dimensions, account.validators.validate_avatar_size], verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='brithday',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
    ]
