# Generated by Django 5.1.5 on 2025-03-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_passwordresettoken_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Medical_system_code',
            field=models.CharField(max_length=12, verbose_name='کد نظام پزشکی'),
        ),
    ]
