# Generated by Django 5.1.5 on 2025-03-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_doctor_medical_system_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن')], max_length=6, null=True, verbose_name='جنسیت'),
        ),
    ]
