# Generated by Django 5.1.5 on 2025-05-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_otpcode_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.UUIDField(default='dCP4nS7OJcwMSkE8PiVILvb2xzflf5ZDBv2VqJJAvkhaL646gdAtusNv9asY79IceTHLR17W', unique=True),
        ),
    ]
