# Generated by Django 5.1.5 on 2025-05-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_passwordresettoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default='kbj8iMsHbZli35w8wR1V2otrISyIJ5gKViZcrL5U312OnGFvkCw0j8SLtUV9bdVf1dWTEh3g', max_length=100, unique=True),
        ),
    ]
