# Generated by Django 5.1.5 on 2025-05-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_passwordresettoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default='OgrR31OBVvhtB9qfIIpqfPHCHjCqJtLKYcOnc8CceNouoe9p1IYs8D0P4O0lr4HskkJEJj1n', max_length=100, unique=True),
        ),
    ]
