# Generated by Django 5.1.5 on 2025-05-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_passwordresettoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default='PB1WWhWzgiJtsOJcPzRj0v3SZ46FvEpmCTSW8xtu5vwpVGQlKvrSJnzj90JMm5lcFrVpEOogRMfzLOd7APr3L6umAnpcMRciPEd7Q79XGVJQXx7IGJHkGzSFh7ff6t375gx5X37Uhqp85v92N81TEpcoYe1JhEudSMU9RGvDIR7xKhSO4ItjnNXXndSxWZBwqNV8fHQ1DEtdEiwOJPAbw7kLcrEcOx637J8yx9CSHUqADWT14o4DkNctnq', max_length=300, unique=True),
        ),
    ]
