# Generated by Django 5.1.5 on 2025-05-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_passwordresettoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default='kCY7eP7tE85xVq6qGJgz5necogkFaMibExBGVS1aKzVRWts7fc29pTRkbOBF9J67v3DFIJWYmSMZTNLQZTHV2TABpaxdMcU19U5J8pOHGYm1pb9ZWj4YYRQLW0M1fOkRDy3Vpd9V5BPoJECxU8Xysk7EZAdHELXEjHtyCfFS6r13S2xFTYq6WMTVnGfElGq3MnG51Aa8SOFjwtvlkFlLo0hukxY6JGzvkmuoBDIlCppipAHEP4kwRUOsMK', max_length=300, unique=True),
        ),
    ]
