# Generated by Django 5.1.5 on 2025-06-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_passwordresettoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('ORTHO', 'ارتودانتیکس'), ('PERIO', 'پریودانتیکس'), ('ENDO', 'اندودانتیکس'), ('PROS', 'پروتزهای دندانی'), ('OMFS', 'جراحی فک و صورت'), ('PED', 'دندانپزشکی کودکان'), ('REST', 'دندانپزشکی ترمیمی و زیبایی'), ('OMFR', 'رادیولوژی فک و صورت'), ('OMFP', 'آسیب\u200cشناسی فک و صورت'), ('DPH', 'بهداشت عمومی دندان'), ('IMPL', 'ایمپلنتولوژی')], max_length=30, verbose_name='تخصص'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default='r0VdkYQhcAjNKOGAIMc6SRRVvjt0bsQu1bKDj3wCyACaqvgKAQZDusuYmNzN7SAJnepnzOssQQSXdxhAe92BYkBCWRI1PwOFtGWZ9L4DnkuZJ5IZAusae0HZ69KCb7hDxF7yrRjCGYtD2fAdrRjGdcWMCoFPxxcdcN7sS9j203qOsvxbAkmFDSf8qkN3prP7l8Zt7TjTeJtmsEqNTHyxBHMvKRZA7HWHezexZgPd9QlfE7leWiX4JEfkI1', max_length=300, unique=True),
        ),
    ]
