# Generated by Django 5.1.5 on 2025-01-27 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_otpcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'تاریخ نوبت',
                'verbose_name_plural': 'تاریخچه نوبت ها',
                'ordering': ('-day',),
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='ساعت')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='ثبت شده')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='account.doctor', verbose_name='پزشک')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='account.patient', verbose_name='بیمار')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_date', to='appointment.appointmentday', verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت ها',
                'ordering': ('-date', '-time'),
            },
        ),
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_dates', to='appointment.appointmentday', verbose_name='تاریخ')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='account.doctor', verbose_name='پزشک')),
            ],
            options={
                'verbose_name': 'زمان در دسترس',
                'verbose_name_plural': 'زمان\u200cهای در دسترس',
                'ordering': ('-date', '-start_time'),
            },
        ),
    ]
