# Generated by Django 5.1.5 on 2025-02-07 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField(verbose_name='درباره ما')),
                ('contact_us', models.TextField(verbose_name='ارتباط با ما')),
                ('copyright', models.TextField(verbose_name='متن کپی رایت')),
                ('logo_site', models.ImageField(upload_to='images/logo_site', verbose_name='لوگو سایت')),
            ],
            options={
                'verbose_name': 'اضافه کردن درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
        migrations.CreateModel(
            name='FooterBoxLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام لینک')),
            ],
            options={
                'verbose_name': 'نام لینک فوتر',
                'verbose_name_plural': 'نام های لینکهای فوتر',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام مجوز')),
                ('icon', models.ImageField(upload_to='images/icon_license', verbose_name='عکس مجوز')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک مجوز')),
            ],
            options={
                'verbose_name': 'مجوز',
                'verbose_name_plural': 'مجوزها',
            },
        ),
        migrations.CreateModel(
            name='socialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='فیسبوک')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='تلگرام')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='توییتر')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='واتس اپ')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='اینستاگرام')),
            ],
            options={
                'verbose_name': 'اضافه کردن لینک فضای مجازی',
                'verbose_name_plural': 'سوشال مدیا',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='لینک')),
                ('footer_box_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer', to='headerfooterapi.footerboxlink', verbose_name='نام لینک فوتر')),
            ],
            options={
                'verbose_name': 'لینک',
                'verbose_name_plural': 'لینک ها',
            },
        ),
    ]
