# Generated by Django 5.1.5 on 2025-06-29 09:32

import django.core.validators
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMagazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='آخرین آپدیت')),
                ('name', models.CharField(max_length=200, verbose_name='نام دسته بندی')),
                ('publish', models.BooleanField(default=True, verbose_name='منتشر شود')),
            ],
            options={
                'verbose_name': 'اضافه کردن یا ویرایش دسته بندی',
                'verbose_name_plural': 'دسته بندی مجله ها',
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='آخرین آپدیت')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان مجله')),
                ('slug', models.SlugField(allow_unicode=True, max_length=80, unique=True, verbose_name='اسلاگ')),
                ('content', models.TextField(verbose_name='متن مقاله')),
                ('status', models.CharField(choices=[('draft', 'پیش نویس مقاله'), ('publish', 'انتشار مقاله')], default='publish', max_length=30, verbose_name='وضعیت')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_blog', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='magazine.categorymagazine', verbose_name='دسته بندی')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'مجله',
                'verbose_name_plural': 'مجلات',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('body', models.TextField(verbose_name='متن دیدگاه')),
                ('rating', models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_review', to='magazine.magazine', verbose_name='مقاله')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='magazine.review', verbose_name='پاسخ دیدگاه')),
            ],
            options={
                'verbose_name': 'دیدگاه',
                'verbose_name_plural': 'دیدگاه ها',
                'ordering': ('-create_at',),
            },
        ),
    ]
