# Generated by Django 5.1.5 on 2025-07-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_magazine', verbose_name='تصویر مقاله'),
        ),
    ]
