# Generated by Django 5.1.5 on 2025-02-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش نویس مقاله'), ('publish', 'انتشار مقاله')], default='publish', max_length=30, verbose_name='وضعیت'),
        ),
    ]
