# Generated by Django 5.1.5 on 2025-06-29 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='آخرین آپدیت')),
                ('tracking_code', models.CharField(editable=False, max_length=10, unique=True, verbose_name='کد رهگیری')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('confirmed', 'تایید شده'), ('cancelled', 'لغو شده'), ('completed', 'انجام شده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='appointment.appointment', verbose_name='نوبت')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.doctor', verbose_name='پزشک')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'سفارش نوبت',
                'verbose_name_plural': 'سفارش\u200cهای نوبت',
                'ordering': ('-create_at',),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ ویزیت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='order.appointmentorder', verbose_name='نوبت')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
                'ordering': ('-create_at',),
            },
        ),
    ]
